In [1]:
import pandas as pd

In [3]:
dui_csv = pd.read_csv("Raw Data/DUI(calculations).csv")
dui_csv.head()

,State,DUI,Fatalities,Population,Sunday.Sales,Fatality.Rate,DUI.Rate,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Alabama,7863.0,247.0,4858979.0,Prohibited,0.000051,0.008509,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alaska,3163.0,24.0,738432.0,Permitted,0.000066,0.008391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arizona,22367.0,272.0,6828065.0,Permitted,0.000096,0.005386,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arkansas,6919.0,149.0,2978204.0,Local,0.000028,0.004685,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,California,141458.0,914.0,39144818.0,Permitted,0.000039,0.004330,NaN,NaN,NaN,NaN,NaN,NaN,NaN